#!/usr/bin/env bash
# Regenerate NuGet.config from the installed Godot Mono package.
# Arch/official distributions ship the SDK as a local .nupkg feed.
set -euo pipefail

cd "$(dirname "$0")/.."

bin="$(command -v godot-mono || command -v godot4-mono || true)"
if [ -z "$bin" ]; then
  echo "godot-mono not found on PATH" >&2
  exit 1
fi

# Arch and official Godot distributions: use the bundled local NuGet feed.
bin_dir="$(dirname "$(readlink -f "$bin")")"
local_feed="$bin_dir/GodotSharp/Tools/nupkgs"
if [ -d "$local_feed" ]; then
  cat > NuGet.config <<EOF
<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by tools/setup-nuget.sh. Re-run after moving or updating Godot. -->
<configuration>
  <packageSources>
    <clear />
    <add key="godot-local" value="$local_feed" />
    <add key="nuget.org" value="https://api.nuget.org/v3/index.json" />
  </packageSources>
  <fallbackPackageFolders>
    <clear />
  </fallbackPackageFolders>
</configuration>
EOF
  echo "NuGet.config -> $local_feed"
  exit 0
fi

echo "Could not locate the engine's bundled NuGet feed: $local_feed" >&2
echo "Install Godot Mono with its GodotSharp/Tools/nupkgs directory intact." >&2
exit 1
